/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exercice6 */

#ifndef _Included_Exercice6
#define _Included_Exercice6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exercice6
 * Method:    fib
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Exercice6_fib
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
