/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exercice5 */

#ifndef _Included_Exercice5
#define _Included_Exercice5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exercice5
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Exercice5_toString
  (JNIEnv *, jobject);

/*
 * Class:     Exercice5
 * Method:    stringFromCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Exercice5_stringFromCpp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
