/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaFromC */

#ifndef _Included_JavaFromC
#define _Included_JavaFromC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaFromC
 * Method:    callJavaMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaFromC_callJavaMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
