/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MessageScanner */

#ifndef _Included_MessageScanner
#define _Included_MessageScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MessageScanner
 * Method:    printCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MessageScanner_printCpp
  (JNIEnv *, jclass);

/*
 * Class:     MessageScanner
 * Method:    printStringToCpp
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MessageScanner_printStringToCpp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     MessageScanner
 * Method:    stringFromCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MessageScanner_stringFromCpp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
