/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Exercice4 */

#ifndef _Included_Exercice4
#define _Included_Exercice4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Exercice4
 * Method:    callJavaMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Exercice4_callJavaMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
