/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo2 */

#ifndef _Included_exo2
#define _Included_exo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo2
 * Method:    getPid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_exo2_getPid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
