/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo4 */

#ifndef _Included_exo4
#define _Included_exo4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo4
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo4_fork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
